"use strict";

const assert = require("node:assert/strict");
const childProcess = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");

const { compile } = require("../src/compiler");
const { parse } = require("../src/parser");
const { analyze } = require("../src/semantics");

const fixturesDir = path.join(__dirname, "fixtures");
const projectRoot = path.join(__dirname, "..");

function readFixture(name) {
  return fs.readFileSync(path.join(fixturesDir, name), "utf8");
}

function compileSource(source, sourcePath) {
  const result = compile(source, { sourcePath });

  assert.deepEqual(result.diagnostics, []);
  assert.equal(typeof result.code, "string");
  assert.notEqual(result.code.length, 0);

  return result.code;
}

function analyzeSource(source, sourcePath) {
  const parseResult = parse(source, { sourcePath });
  assert.deepEqual(parseResult.diagnostics, []);

  const semanticResult = analyze(parseResult.program, { sourcePath });
  assert.deepEqual(semanticResult.diagnostics, []);

  return semanticResult.program || parseResult.program;
}

function runGenerated(code) {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "basic-codegen-"));
  const outputPath = path.join(tempDir, "program.js");
  fs.writeFileSync(outputPath, code, "utf8");

  return childProcess.execFileSync(process.execPath, [outputPath], {
    encoding: "utf8",
  });
}

function runGeneratedResult(code, options = {}) {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "basic-codegen-"));
  const outputPath = path.join(tempDir, "program.js");
  fs.writeFileSync(outputPath, code, "utf8");

  return childProcess.spawnSync(process.execPath, [outputPath], {
    encoding: "utf8",
    input: options.input,
  });
}

function compileWithCli(source, basename) {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "basic-cli-"));
  const sourcePath = path.join(tempDir, `${basename}.bas`);
  const outputPath = path.join(tempDir, `${basename}.js`);
  fs.writeFileSync(sourcePath, source, "utf8");

  const result = childProcess.spawnSync(process.execPath, [path.join(projectRoot, "src", "cli.js"), "compile", sourcePath, "--out", outputPath], {
    encoding: "utf8",
  });

  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.equal(result.stderr, "");
  assert.equal(fs.existsSync(outputPath), true);

  return outputPath;
}

test("compile emits deterministic readable JavaScript without eval or timestamps", () => {
  const sourcePath = path.join(fixturesDir, "codegen-linear.bas");
  const source = readFixture("codegen-linear.bas");
  const first = compileSource(source, sourcePath);
  const second = compileSource(source, sourcePath);

  assert.equal(first, second);
  assert.match(first, /Generated by basic-js-compiler/);
  assert.match(first, new RegExp(`Source: ${escapeRegExp(sourcePath)}`));
  assert.doesNotMatch(first, /\beval\s*\(/);
  assert.doesNotMatch(first, /\bnew Function\b/);
  assert.doesNotMatch(first, /\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  assert.match(first, /while\s*\(\s*pc\s*<\s*statements\.length\s*\)/);
  assert.match(first, /switch\s*\(\s*pc\s*\)/);
  assert.match(first, /case\s+0\s*:/);
  assert.match(first, /pc\s*\+=\s*1/);
  assert.match(first, /vars(?:\.|\["?)A(?:\b|"?\])\s*=/);
  assert.match(first, /1\s*\+\s*\(?2\s*\*\s*3\)?/);
  assert.match(first, /VALUE/);
  assert.match(first, /NAME=/);
});

test("generate emits the same deterministic structural code from an analyzed program", () => {
  const { generate } = require("../src/codegen");
  const sourcePath = path.join(fixturesDir, "codegen-linear.bas");
  const program = analyzeSource(readFixture("codegen-linear.bas"), sourcePath);
  const first = generate(program, { sourcePath });
  const second = generate(program, { sourcePath });

  assert.equal(first, second);
  assert.match(first, /Source:/);
  assert.match(first, /const\s+labels\s*=/);
  assert.match(first, /while\s*\(\s*pc\s*<\s*statements\.length\s*\)/);
  assert.match(first, /switch\s*\(\s*pc\s*\)/);
  assert.doesNotMatch(first, /\beval\s*\(/);
});

test("generated fixture preserves PRINT comma, semicolon, newline, and STOP behavior", () => {
  const sourcePath = path.join(fixturesDir, "codegen-linear.bas");
  const code = compileSource(readFixture("codegen-linear.bas"), sourcePath);

  assert.equal(runGenerated(code), "VALUE 7\nNAME=Ada\n");
});

test("generated unary exponent expression runs with BASIC precedence", () => {
  const sourcePath = path.join(fixturesDir, "codegen-unary-exponent.bas");
  const code = compileSource(readFixture("codegen-unary-exponent.bas"), sourcePath);

  assert.doesNotMatch(code, /-2\s*\*\*\s*2/);
  assert.equal(runGenerated(code), "-4\n");
});

test("compiled hello example runs directly in Node", () => {
  const sourcePath = path.join(projectRoot, "examples", "hello.bas");
  const source = fs.readFileSync(sourcePath, "utf8");
  const code = compileSource(source, sourcePath);

  assert.equal(runGenerated(code), "HELLO FROM BASIC\n");
});

test("generated branching fixture resolves labels and program counter transitions", () => {
  const sourcePath = path.join(fixturesDir, "branching.bas");
  const code = compileSource(readFixture("branching.bas"), sourcePath);

  assert.match(code, /const\s+gosubStack\s*=\s*\[\]/);
  assert.match(code, /"200"\s*:\s*\d+/);
  assert.match(code, /pc\s*=\s*labels\["?200"?\]/);
  assert.match(code, /gosubStack\.push\(pc\s*\+\s*1\)/);
  assert.match(code, /pc\s*=\s*gosubStack\.pop\(\)/);
  assert.equal(runGenerated(code), "START\nFORWARD\nCOUNT 1\nCOUNT 2\nCOUNT 3\nSUB A\nSUB B\nDONE\n");
});

test("generated code handles finite backward jumps", () => {
  const sourcePath = path.join(fixturesDir, "branching-backward.bas");
  const code = compileSource(readFixture("branching-backward.bas"), sourcePath);

  assert.equal(runGenerated(code), "LOOP 1\nLOOP 2\nLOOP 3\nEXIT\n");
});

test("generated code preserves nested GOSUB return order", () => {
  const sourcePath = path.join(fixturesDir, "branching-nested-gosub.bas");
  const code = compileSource(readFixture("branching-nested-gosub.bas"), sourcePath);

  assert.equal(runGenerated(code), "MAIN\nSUB1\nSUB2\nSUB1 DONE\nMAIN DONE\n");
});

test("generated nested IF PRINT includes required runtime helpers", () => {
  const sourcePath = path.join(fixturesDir, "codegen-nested-if-print.bas");
  const code = compileSource('IF 1 THEN PRINT "X"\n', sourcePath);

  assert.equal(runGenerated(code), "X\n");
});

test("generated nested IF RETURN reports BASIC runtime error", () => {
  const sourcePath = path.join(fixturesDir, "codegen-nested-if-return.bas");
  const code = compileSource("IF 1 THEN RETURN\n", sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.equal(result.stderr, "BASIC runtime error BASRT002: RETURN without GOSUB\n");
  assert.doesNotMatch(result.stderr, /ReferenceError/);
});

test("generated RETURN without GOSUB exits with a runtime stack error", () => {
  const sourcePath = path.join(fixturesDir, "branching-return-without-gosub.bas");
  const code = compileSource(readFixture("branching-return-without-gosub.bas"), sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /RETURN|GOSUB|stack/i);
});

test("generated loops fixture handles nesting, omitted NEXT variable, and STEP directions", () => {
  const sourcePath = path.join(fixturesDir, "loops.bas");
  const code = compileSource(readFixture("loops.bas"), sourcePath);

  assert.match(code, /const\s+forStack\s*=\s*\[\]/);
  assert.match(code, /STEP|step|forStack/);
  assert.equal(runGenerated(code), "LOOPS\n1:4\n1:3\n1:2\n2:4\n2:3\n2:2\n3:4\n3:3\n3:2\n2\n4\n6\n");
});

test("generated FOR STEP 0 exits with a runtime error", () => {
  const sourcePath = "step-zero.bas";
  const code = compileSource("10 FOR I = 1 TO 3 STEP 0\n20 PRINT I\n30 NEXT I\n", sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /STEP|zero|0/i);
});

test("generated arrays fixture supports DIM, inclusive bounds, numeric arrays, and string arrays", () => {
  const sourcePath = path.join(fixturesDir, "arrays.bas");
  const code = compileSource(readFixture("arrays.bas"), sourcePath);

  assert.match(code, /const\s+arrays\s*=/);
  assert.match(code, /NAME\$/);
  assert.equal(runGenerated(code), "15 Ada\n");
});

test("generated DIM rejects invalid array upper bounds at runtime", () => {
  const sourcePath = "invalid-dim-bound.bas";
  const code = compileSource("10 DIM A(-1)\n20 PRINT A(0)\n", sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /bound|DIM|array/i);
});

test("generated array access rejects non-integer indexes at runtime", () => {
  const sourcePath = "non-integer-array-index.bas";
  const code = compileSource("10 DIM A(2)\n20 A(1.5) = 7\n", sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /integer|index/i);
});

test("generated array access rejects out-of-bounds indexes at runtime", () => {
  const sourcePath = "array-out-of-bounds.bas";
  const code = compileSource("10 DIM A(2)\n20 PRINT A(3)\n", sourcePath);
  const result = runGeneratedResult(code);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /bounds|index|array/i);
});

test("generated numeric INPUT reads piped stdin and prompts before output", () => {
  const sourcePath = "input-number.bas";
  const code = compileSource('10 INPUT "NUMBER"; N\n20 PRINT N + 2\n', sourcePath);
  const result = runGeneratedResult(code, { input: "40\n" });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.match(result.stdout, /^NUMBER/);
  assert.match(result.stdout, /42\n$/);
});

test("generated numeric INPUT prompt separates from following PRINT output", () => {
  const sourcePath = "input-prompt-print-number.bas";
  const code = compileSource('10 INPUT "YOUR GUESS"; G\n20 IF G = 7 THEN PRINT "RIGHT" ELSE PRINT "WRONG"\n', sourcePath);
  const result = runGeneratedResult(code, { input: "7\n" });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "YOUR GUESS RIGHT\n");
});

test("generated string INPUT preserves piped text and comma prompts", () => {
  const sourcePath = "input-string.bas";
  const code = compileSource('10 INPUT "NAME", NAME$\n20 PRINT "HELLO "; NAME$\n', sourcePath);
  const result = runGeneratedResult(code, { input: "Ada Lovelace\n" });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.match(result.stdout, /^NAME/);
  assert.match(result.stdout, /HELLO Ada Lovelace\n$/);
});

test("generated string INPUT prompt separates from following PRINT output", () => {
  const sourcePath = "input-prompt-print-string.bas";
  const code = compileSource('10 INPUT "NAME"; NAME$\n20 PRINT "HELLO "; NAME$\n', sourcePath);
  const result = runGeneratedResult(code, { input: "Ada\n" });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.equal(result.stdout, "NAME HELLO Ada\n");
});

test("generated numeric INPUT rejects invalid piped input at runtime", () => {
  const sourcePath = "input-invalid-number.bas";
  const code = compileSource("10 INPUT N\n20 PRINT N\n", sourcePath);
  const result = runGeneratedResult(code, { input: "not-a-number\n" });

  assert.equal(result.status, 1);
  assert.match(result.stderr, /^BASIC runtime error BASRT009: /);
  assert.match(result.stderr, /BASIC runtime error/i);
  assert.match(result.stderr, /input|number|numeric/i);
});

test("CLI-generated INPUT program runs with piped stdin", () => {
  const source = '10 INPUT "GUESS", G\n20 IF G = 7 THEN PRINT "YES" ELSE PRINT "NO"\n30 END\n';
  const outputPath = compileWithCli(source, "guess-input");
  const result = childProcess.spawnSync(process.execPath, [outputPath], {
    encoding: "utf8",
    input: "7\n",
  });

  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
  assert.match(result.stdout, /^GUESS/);
  assert.match(result.stdout, /YES\n$/);
});

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
