"use strict";

const { createRuntimeTemplate } = require("./runtime-template");

function generate(program, options = {}) {
  const sourcePath = options.sourcePath || program.sourcePath || "<unknown>";
  const features = collectFeatures(program);
  const labels = Object.create(null);

  for (const [label, index] of program.labels.entries()) {
    labels[label] = index;
  }

  const lines = [
    '"use strict";',
    "",
    "// Generated by basic-js-compiler 0.1.0.",
    `// Source: ${sourcePath}`,
    "// Compiler metadata: deterministic, timestamp-free output.",
    "",
    "function main() {",
    "  let pc = 0;",
    "  const vars = Object.create(null);",
    "  const arrays = Object.create(null);",
    "  const gosubStack = [];",
    "  const forStack = [];",
    `  const labels = ${formatLabels(labels)};`,
    `  const statements = new Array(${program.statements.length});`,
  ];

  const runtimeTemplate = createRuntimeTemplate(features);
  if (runtimeTemplate) {
    lines.push("", indent(runtimeTemplate, 2));
  }
  lines.push("", "  while (pc < statements.length) {", "    switch (pc) {");

  program.statements.forEach((statement, index) => {
    lines.push(`      case ${index}:`);
    lines.push(`        // BASIC line ${statement.sourceLine}: ${statement.type}`);
    for (const statementLine of emitStatement(statement)) {
      lines.push(`        ${statementLine}`);
    }
    lines.push("        break;");
  });

  lines.push(
    "      default:",
    "        pc = statements.length;",
    "        break;",
    "    }",
    "  }",
    "}",
    "",
    "main();",
    "",
  );

  return lines.join("\n");
}

function emitStatement(statement) {
  switch (statement.type) {
    case "AssignmentStatement":
      return emitAssignmentStatement(statement);
    case "PrintStatement":
      return emitPrintStatement(statement);
    case "InputStatement":
      return emitInputStatement(statement);
    case "IfStatement":
      return emitIfStatement(statement);
    case "GotoStatement":
      return [`pc = labels[${quote(String(statement.targetLabel))}];`];
    case "GosubStatement":
      return [`gosubStack.push(pc + 1);`, `pc = labels[${quote(String(statement.targetLabel))}];`];
    case "ReturnStatement":
      return ["if (gosubStack.length === 0) {", "  runtimeError(\"BASRT002\", \"RETURN without GOSUB\");", "}", "pc = gosubStack.pop();"];
    case "ForStatement":
      return emitForStatement(statement);
    case "NextStatement":
      return emitNextStatement(statement);
    case "DimStatement":
      return [`arrays[${quote(statement.name)}] = createArray(${emitExpression(statement.upperBound)}, ${quote(statement.valueType)});`, "pc += 1;"];
    case "EndStatement":
    case "StopStatement":
      return ["pc = statements.length;"];
    case "CommentStatement":
      return ["pc += 1;"];
    default:
      return [`runtimeError("BASRT999", "Unsupported generated statement: ${escapeForDoubleQuotedString(statement.type)}");`];
  }
}

function emitAssignmentStatement(statement) {
  if (statement.target.type === "ArrayTarget") {
    return [`writeArray(${quote(statement.target.name)}, ${emitExpression(statement.target.indexes[0])}, ${emitExpression(statement.expression)});`, "pc += 1;"];
  }
  return [`vars[${quote(statement.target.name)}] = ${emitExpression(statement.expression)};`, "pc += 1;"];
}

function emitInputStatement(statement) {
  const valueType = statement.target.valueType || (statement.target.name.endsWith("$") ? "string" : "number");
  const lines = [];
  if (statement.prompt) {
    lines.push(`process.stdout.write(${emitInputPrompt(statement)});`);
  }
  if (statement.target.type === "ArrayTarget") {
    lines.push(`writeArray(${quote(statement.target.name)}, ${emitExpression(statement.target.indexes[0])}, inputValue(${quote(valueType)}));`);
  } else {
    lines.push(`vars[${quote(statement.target.name)}] = inputValue(${quote(valueType)});`);
  }
  lines.push("pc += 1;");
  return lines;
}

function emitInputPrompt(statement) {
  if (statement.prompt.type === "StringLiteral" && (statement.promptSeparator === ";" || statement.promptSeparator === ",")) {
    const prompt = statement.prompt.value;
    return quote(/\s$/.test(prompt) ? prompt : `${prompt} `);
  }
  return emitExpression(statement.prompt);
}

function emitForStatement(statement) {
  const variableName = quote(statement.variable.name);
  const start = emitExpression(statement.start);
  const end = emitExpression(statement.end);
  const step = statement.step ? emitExpression(statement.step) : "1";
  return [
    "{",
    `  const startValue = ${start};`,
    `  const endValue = ${end};`,
    `  const stepValue = ${step};`,
    "  if (stepValue === 0) {",
    "    runtimeError(\"BASRT003\", \"FOR STEP cannot be 0\");",
    "  }",
    `  vars[${variableName}] = startValue;`,
    "  if ((stepValue > 0 && startValue > endValue) || (stepValue < 0 && startValue < endValue)) {",
    `    pc = ${statement.matchingNextIndex + 1};`,
    "  } else {",
    `    forStack.push({ variable: ${variableName}, end: endValue, step: stepValue, forIndex: pc, nextIndex: ${statement.matchingNextIndex} });`,
    "    pc += 1;",
    "  }",
    "}",
  ];
}

function emitNextStatement(statement) {
  return [
    "{",
    "  const frame = forStack[forStack.length - 1];",
    "  if (!frame || frame.nextIndex !== pc) {",
    "    runtimeError(\"BASRT004\", \"NEXT without active FOR\");",
    "  }",
    "  vars[frame.variable] = readVar(frame.variable, \"number\") + frame.step;",
    "  const value = vars[frame.variable];",
    "  if ((frame.step > 0 && value <= frame.end) || (frame.step < 0 && value >= frame.end)) {",
    "    pc = frame.forIndex + 1;",
    "  } else {",
    "    forStack.pop();",
    "    pc += 1;",
    "  }",
    "}",
  ];
}

function emitIfStatement(statement) {
  const lines = [`if (basicTruth(${emitExpression(statement.test)})) {`];
  lines.push(...indentLines(emitBranchTarget(statement.thenBranch), 2));
  if (statement.elseBranch) {
    lines.push("} else {");
    lines.push(...indentLines(emitBranchTarget(statement.elseBranch), 2));
  }
  lines.push("}");
  lines.push("pc += 1;");
  return lines;
}

function emitBranchTarget(branch) {
  if (!branch) {
    return [];
  }
  if (branch.type === "LineNumberBranch") {
    return [`pc = labels[${quote(String(branch.targetLabel))}];`, "continue;"];
  }
  return emitStatement(branch).concat("continue;");
}

function emitPrintStatement(statement) {
  if (statement.items.length === 0) {
    return statement.trailingSeparator === ";" ? ["pc += 1;"] : ['process.stdout.write("\\n");', "pc += 1;"];
  }

  const lines = [];
  for (const item of statement.items) {
    lines.push(`printValue(${emitExpression(item.expression || item)});`);
    if (item.separator === ",") {
      lines.push('process.stdout.write(" ");');
    }
  }
  if (statement.trailingSeparator !== ";") {
    lines.push('process.stdout.write("\\n");');
  }
  lines.push("pc += 1;");
  return lines;
}

function emitExpression(expression, parentPrecedence = 0, parentOperator = null, side = null) {
  switch (expression.type) {
    case "NumericLiteral":
      return Number.isFinite(expression.value) ? String(expression.value) : "0";
    case "StringLiteral":
      return quote(expression.value);
    case "IdentifierExpression":
      return `readVar(${quote(expression.name)}, ${quote(expression.valueType || (expression.name.endsWith("$") ? "string" : "number"))})`;
    case "ArrayExpression":
      return `readArray(${quote(expression.name)}, ${emitExpression(expression.indexes[0])})`;
    case "GroupingExpression":
      return `(${emitExpression(expression.expression)})`;
    case "UnaryExpression":
      return emitUnaryExpression(expression, parentPrecedence);
    case "BinaryExpression":
      return emitBinaryExpression(expression, parentPrecedence, parentOperator, side);
    case "CallExpression":
      return emitCallExpression(expression);
    default:
      return `runtimeError("BASRT998", "Unsupported generated expression: ${escapeForDoubleQuotedString(expression.type)}")`;
  }
}

function emitUnaryExpression(expression, parentPrecedence) {
  const precedence = 6;
  let argument = emitExpression(expression.argument, precedence);
  let code;
  if (expression.operator === "NOT") {
    code = `!basicTruth(${argument})`;
  } else {
    if (expression.argument.type === "BinaryExpression" && expression.argument.operator === "^") {
      argument = `(${argument})`;
    }
    code = `${expression.operator}${argument}`;
  }
  return precedence < parentPrecedence ? `(${code})` : code;
}

function emitBinaryExpression(expression, parentPrecedence, parentOperator, side) {
  const precedence = binaryPrecedence(expression.operator);
  const left = emitExpression(expression.left, precedence, expression.operator, "left");
  const right = emitExpression(expression.right, precedence, expression.operator, "right");
  let code;
  switch (expression.operator) {
    case "=":
      code = `${left} === ${right}`;
      break;
    case "<>":
      code = `${left} !== ${right}`;
      break;
    case "AND":
      code = `basicTruth(${left}) && basicTruth(${right})`;
      break;
    case "OR":
      code = `basicTruth(${left}) || basicTruth(${right})`;
      break;
    case "^":
      code = `${left} ** ${right}`;
      break;
    default:
      code = `${left} ${expression.operator} ${right}`;
      break;
  }

  if (needsBinaryParens(expression.operator, precedence, parentPrecedence, parentOperator, side)) {
    return `(${code})`;
  }
  return code;
}

function binaryPrecedence(operator) {
  switch (operator) {
    case "OR":
      return 1;
    case "AND":
      return 2;
    case "=":
    case "<>":
    case "<":
    case "<=":
    case ">":
    case ">=":
      return 3;
    case "+":
    case "-":
      return 4;
    case "*":
    case "/":
      return 5;
    case "^":
      return 7;
    default:
      return 0;
  }
}

function needsBinaryParens(operator, precedence, parentPrecedence, parentOperator, side) {
  if (precedence < parentPrecedence) {
    return true;
  }
  if (precedence > parentPrecedence) {
    return false;
  }
  if (side !== "right") {
    return false;
  }
  return parentOperator === "-" || parentOperator === "/" || parentOperator === "^" || operator === "^";
}

function emitCallExpression(expression) {
  const args = expression.args.map(emitExpression);
  switch (expression.callee) {
    case "ABS":
      return `Math.abs(${args[0]})`;
    case "INT":
      return `Math.floor(${args[0]})`;
    case "LEN":
      return `String(${args[0]}).length`;
    case "LEFT$":
      return `String(${args[0]}).slice(0, ${args[1]})`;
    case "RIGHT$":
      return `String(${args[0]}).slice(-${args[1]})`;
    case "MID$":
      return `String(${args[0]}).slice(${args[1]} - 1, (${args[1]} - 1) + ${args[2]})`;
    case "STR$":
      return `String(${args[0]})`;
    case "VAL":
      return `val(${args[0]})`;
    case "RND":
      return "rnd()";
    default:
      return `runtimeError("BASRT997", "Unsupported generated call: ${escapeForDoubleQuotedString(expression.callee)}")`;
  }
}

function collectFeatures(program) {
  const features = {
    basicTruth: false,
    printValue: false,
    readVar: false,
    arrays: false,
    input: false,
    rnd: false,
    runtimeError: false,
    val: false,
  };
  walkStatements(program.statements, (statement) => {
    if (statement.type === "PrintStatement" && statement.items.length > 0) {
      features.printValue = true;
    }
    walkStatementExpressions(statement, (expression) => {
      if (expression.type === "IdentifierExpression") {
        features.readVar = true;
      } else if (expression.type === "ArrayExpression") {
        features.arrays = true;
        features.runtimeError = true;
      } else if (expression.type === "UnaryExpression" && expression.operator === "NOT") {
        features.basicTruth = true;
      } else if (expression.type === "BinaryExpression" && (expression.operator === "AND" || expression.operator === "OR")) {
        features.basicTruth = true;
      } else if (expression.type === "CallExpression") {
        if (expression.callee === "RND") {
          features.rnd = true;
        } else if (expression.callee === "VAL") {
          features.val = true;
          features.runtimeError = true;
        }
      }
    });
    if (statement.type === "IfStatement") {
      features.basicTruth = true;
    } else if (statement.type === "InputStatement") {
      features.input = true;
      features.runtimeError = true;
      if (statement.target && statement.target.type === "ArrayTarget") {
        features.arrays = true;
      }
    } else if (statement.type === "ReturnStatement") {
      features.runtimeError = true;
    } else if (statement.type === "ForStatement") {
      features.readVar = true;
      features.runtimeError = true;
    } else if (statement.type === "NextStatement") {
      features.readVar = true;
      features.runtimeError = true;
    } else if (statement.type === "DimStatement") {
      features.arrays = true;
      features.runtimeError = true;
    } else if (statement.type === "AssignmentStatement" && statement.target.type === "ArrayTarget") {
      features.arrays = true;
      features.runtimeError = true;
    }
  });
  return features;
}

function walkStatements(statements, visit) {
  for (const statement of statements) {
    visit(statement);
    if (statement.type === "IfStatement") {
      walkBranchStatement(statement.thenBranch, visit);
      walkBranchStatement(statement.elseBranch, visit);
    }
  }
}

function walkBranchStatement(branch, visit) {
  if (branch && branch.type !== "LineNumberBranch") {
    walkStatements([branch], visit);
  }
}

function walkStatementExpressions(statement, visit) {
  if (statement.type === "AssignmentStatement" && statement.expression) {
    if (statement.target.type === "ArrayTarget") {
      for (const index of statement.target.indexes) {
        walkExpression(index, visit);
      }
    }
    walkExpression(statement.expression, visit);
  }
  if (statement.type === "ForStatement") {
    walkExpression(statement.start, visit);
    walkExpression(statement.end, visit);
    walkExpression(statement.step, visit);
  }
  if (statement.type === "DimStatement") {
    walkExpression(statement.upperBound, visit);
  }
  if (statement.type === "PrintStatement") {
    for (const item of statement.items) {
      walkExpression(item.expression || item, visit);
    }
  }
  if (statement.type === "InputStatement") {
    walkExpression(statement.prompt, visit);
    if (statement.target && statement.target.type === "ArrayTarget") {
      for (const index of statement.target.indexes) {
        walkExpression(index, visit);
      }
    }
  }
  if (statement.type === "IfStatement") {
    walkExpression(statement.test, visit);
  }
}

function walkExpression(expression, visit) {
  if (!expression) {
    return;
  }
  visit(expression);
  if (expression.type === "UnaryExpression") {
    walkExpression(expression.argument, visit);
  } else if (expression.type === "BinaryExpression") {
    walkExpression(expression.left, visit);
    walkExpression(expression.right, visit);
  } else if (expression.type === "GroupingExpression") {
    walkExpression(expression.expression, visit);
  } else if (expression.type === "CallExpression") {
    for (const arg of expression.args) {
      walkExpression(arg, visit);
    }
  } else if (expression.type === "ArrayExpression") {
    for (const index of expression.indexes) {
      walkExpression(index, visit);
    }
  }
}

function formatLabels(labels) {
  const entries = Object.entries(labels);
  if (entries.length === 0) {
    return "Object.freeze({})";
  }
  const fields = entries.map(([label, index]) => `${JSON.stringify(label)}: ${index}`);
  return `Object.freeze({ ${fields.join(", ")} })`;
}

function indent(text, spaces) {
  const prefix = " ".repeat(spaces);
  return text.split("\n").map((line) => (line ? prefix + line : line)).join("\n");
}

function indentLines(lines, spaces) {
  const prefix = " ".repeat(spaces);
  return lines.map((line) => (line ? prefix + line : line));
}

function quote(value) {
  return JSON.stringify(value);
}

function escapeForDoubleQuotedString(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

module.exports = {
  generate,
};
